[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self';"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "picture-in-picture=(), camera=()"
